$ANSIBLE_VAULT;1.1;AES256
37636365396362663566306236313338636661643839666636643364613533613337353066613464
3864653434623732306630393232356238623631373133320a376635336138326661346636363132
34393034363733626330643565353130383738353737666435393833666566343962393032313765
3834323563653838630a306530323833623437376232336664306136343865313139346232363432
32353939346166323863303934316362356632373362663538633463386230316630633262323534
3934653763343562666166343563326130653738306465656465
