---
- name: Configure server
  hosts: production
  gather_facts: no
  tasks:
    - name: Show current hostname
      command: hostname
      register: result

    - name: Print hostname to console
      debug:
        msg: "Connected to {{ result.stdout }} as {{ ansible_user }}"
