services:
  loki:
    image: grafana/loki:2.9.2
    container_name: ${CONTAINER_PREFIX}-o11y-loki
    command: -config.file=/etc/loki/config.yaml -config.expand-env=true
    volumes:
      - ./o11y/loki/config.yaml:/etc/loki/config.yaml:ro,Z
      - loki-data:/loki
    ports:
      - "${O11Y_LOKI_PORT}:${O11Y_LOKI_PORT_HOST}"
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.2
    container_name: ${CONTAINER_PREFIX}-o11y-promtail
    command: -config.file=/etc/promtail/config.yaml -config.expand-env=true
    volumes:
      - ./o11y/promtail/config.yaml:/etc/promtail/config.yaml:ro,Z
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-positions:/tmp
    restart: unless-stopped
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.4.2
    container_name: ${CONTAINER_PREFIX}-o11y-grafana
    ports:
      - "${O11Y_GRAFANA_PORT}:${O11Y_GRAFANA_PORT_HOST}"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - loki

volumes:
  loki-data:
  grafana-data:
  promtail-positions:
