services:
  loki:
    image: grafana/loki:2.9.2
    container_name: o11y-loki
    command:
      - -config.file=/etc/loki/config.yaml
      - -config.expand-env=true
    volumes:
      - ./o11y/loki/config.yaml:/etc/loki/config.yaml:ro,Z
      - loki-data:/loki
    ports:
      - "${O11Y_LOKI_PORT}:${O11Y_LOKI_PORT_HOST}"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.2
    container_name: o11y-promtail
    command: -config.file=/etc/promtail/config.yaml -config.expand-env=true
    volumes:
      - ./o11y/promtail/config.yaml:/etc/promtail/config.yaml:ro,Z
      - /var/lib/docker/containers:/var/lib/docker/containers:ro,Z
      - promtail-positions:/tmp
    restart: unless-stopped
    depends_on:
      loki:
        condition: service_healthy

  grafana:
    image: grafana/grafana:10.4.2
    container_name: o11y-grafana
    ports:
      - "${O11Y_GRAFANA_PORT}:${O11Y_GRAFANA_PORT_HOST}"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./o11y/grafana/datasources:/etc/grafana/provisioning/datasources
    restart: unless-stopped
    depends_on:
      loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  loki-data:
  grafana-data:
  promtail-positions:
