---
compose_project_name: oko

db_connection: pgsql
db_host: db
db_port: 5432
db_port_host: 5432
db_name: oko
db_user: oko
db_password: oko
db_ssl: disable

o11y_loki_port: 3100
o11y_loki_port_host: 3100
o11y_grafana_port: 3000
o11y_grafana_port_host: 3000
