$ANSIBLE_VAULT;1.1;AES256
63333334373736613838626131393736613930616363613565323038376131343138343266303536
6331316639333535383231633631666437353737326338370a346661666164663934386331653939
64636366316362376364643735396330333236393838666666356365363065643436393132376531
3966373432333961340a353763356561323163623435626133626637313435613062343235393932
35346632653730393165353733663063383630303537363033623833316134643762
