compose_project_name: ENC[AES256_GCM,data:q7Tx,iv:Y6c9sZFhXV6/7HTL67IDFSmPgGRYd7z5Thr2CBl9990=,tag:GgnWWvEBy7L7zWVP8lL+oQ==,type:str]
db_connection: ENC[AES256_GCM,data:cN4iwHk=,iv:UbEvchhXj/zjOjBgepWbHBKsmuGGrrV5Ly5i/nO93Sc=,tag:CqD2rCB6gUkBpdk7sMdNMQ==,type:str]
db_host: ENC[AES256_GCM,data:EEs=,iv:nhk85E/Jhz1mnYO5PSWgeT5fj0amW/yxpg+dw6vUa28=,tag:TvqHELOoK8gJ7JPf9LCzWw==,type:str]
db_port: ENC[AES256_GCM,data:XYgdJw==,iv:0wNlT54nTUuMeYaNCYba5VMs4j+OwJ/4k2WU2f3qfjo=,tag:ib0yVik4BzQyQyTtKBwGmw==,type:int]
db_port_host: ENC[AES256_GCM,data:ytoStg==,iv:itGQboQ8cVIvcifH8qWtHIWMExawBapxjAgToefS6io=,tag:e60w1novcH0fUT2zyt6d3Q==,type:int]
db_name: ENC[AES256_GCM,data:3eJP,iv:FdFSj2AAqA3ypw0iAcA5RzeUXwdyFBQbzaVXhBDa0vE=,tag:o+LV8Scq1VojMlA5630P4g==,type:str]
db_user: ENC[AES256_GCM,data:hgY5mkb4Zw==,iv:7Mf6cu3tbIlOPOiGJ1TV6FQPvpcIKKazu+hrWuMxuRo=,tag:dGZfw31LyE2UinQJ8ynYKQ==,type:str]
db_password: ENC[AES256_GCM,data:TRE8rtnUpk2dtg==,iv:tel23ILNeYQbvVy3ph4cr5iUoAC4A3Er6P+rlf2wlKI=,tag:vm2AJZxxW+RdxfXH5jgyDQ==,type:str]
db_ssl: ENC[AES256_GCM,data:E0OW/aX1iQ==,iv:vgzMLrmATmr4lfkL5Rl5mbo/iSq6UZdUZH9jd0G9H3s=,tag:NM7zs6qjEAsI2ARLWrjidg==,type:str]
o11y_loki_port: ENC[AES256_GCM,data:gzBQnA==,iv:Mw7pjGA8q+I2BVqf1yB8SYiPS4LPGW7w1H2VXpxx9/Y=,tag:S1CROs1pGgsuvaAmfV3mpQ==,type:int]
o11y_loki_port_host: ENC[AES256_GCM,data:DjOouQ==,iv:C9Q2eGwXwj52SqsEXIvGYH6I0uFExN2ApT0IeSyhG0o=,tag:9IqTp7Ozjbbkh05T/+CyNg==,type:int]
o11y_grafana_port: ENC[AES256_GCM,data:fHboWA==,iv:n2TNCfWerZmMBOSxZUYuUDq6KtdiRzrjGDnH8jNjNbY=,tag:DwUBGa9htQhEqw8fqeZCjg==,type:int]
o11y_grafana_port_host: ENC[AES256_GCM,data:XwIVzw==,iv:XGlgdVBH1OFP/t7IcQGXkeJqImmCZTGMF5DTefNOZwQ=,tag:V8z4tYhACtF95O212S17GA==,type:int]
sops:
    age:
        - recipient: age1lru73g2m2y9zydfsdlfgvda7xw8qnhwepaydnheq3l6xal4pvqfslr5vht
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcFIweWxxb3daRFd5WWhP
            bStiaXk5VzhEREFobldsUnhERXBVQWNVWFNNCmlPVXExZ1J0VWpkYkpFeXZjSGRi
            NFZUY2JBQTFnVlczOTRtUSt3bHhaZkkKLS0tIGhYeFQ3WWpFU3h3b1FpekFqaUJV
            Ly95cVJMR3JvZnlYeVVwZ2dDY1JlSGMKJG4RXA5fuHgblSQ2QUsDggKs0ag37Z3u
            mOj1VJpzttqBzAJE131PjXDQHx4EXGB28OwqV5BWHYTtKZk0MZQVnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m4v0egh4e94qcns0se3088zdshvp4xurz3gs4pxqk3p60clm85eqgn3j2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTm1wZ24rbUV0dmhCb0RR
            MGJ6T3JhYzkrYlliZzVzY1VyU25YSjh5UUFFCk9mRjFFTE9YQXJEb01Xb09QUzhi
            Q2VSWE9YdnBiZThFYkRyY0tPTWlyU1EKLS0tIG55elI2dmVmVmJMWW56dCttWjdH
            dzIxRlI3Yk53dndYbUM4WENaaVplZXcKDAYUxUrH6bL4loieBPaUEqSvkJkiIxzk
            bHFANJlk/9Pdbik/JovdDKs/eRf+1yiJIZS9d3BhJkX4x43gu5To3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T20:02:36Z"
    mac: ENC[AES256_GCM,data:IKtxc8OdSX8ZI+f/np/7BCKYFma352zXTLnBoRBylHBfLGMdGnSnh50KR1E63e3lUwMAx75XmegbjG956xiViB0fB074pi0BaDgg5IYy7PGlRHFQ6JrdCeoeQfQKz/69Du1HGEvn1MqW679zx/YwxO5jZ+/vOPZClcqX8e33FMQ=,iv:VYqW2hQIYkmFVtjbuK65k9IuPr7WLcI1131wlKMvU7U=,tag:rSrG6mkjOWzsRQR/1lZWhQ==,type:str]
    encrypted_regex: .*
    version: 3.11.0
